services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: newsfeed
      MYSQL_USER: newsuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: ./NewsFeedBackend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Default: Server=db;Port=3306;Database=newsfeed;User Id=newsuser;Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=Preferred
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: NewsFeedBackend
      Jwt__Audience: NewsFeedFrontend
      NewsData__ApiKey: ${NEWSDATA_API_KEY}
      NewsData__DefaultLanguage: en
      NewsData__DefaultCountry: "US"
      NewsData__DefaultCategory: ""
      NewsData__DefaultQuery: ""
      Smtp__Host: ${SMTP_HOST}
      Smtp__Port: ${SMTP_PORT}
      Smtp__Secure: ${SMTP_SECURE}
      Smtp__User: ${SMTP_USER}
      Smtp__Password: ${SMTP_PASSWORD}
      Smtp__FromEmail: ${SMTP_FROM}
      Smtp__FromName: "My Epic News"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:8080"

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "if [ -f package-lock.json ]; then npm ci; else npm install; fi && npm run dev -- --host"
    volumes:
      - ./vite-project:/app
    environment:
      VITE_API_BASE: http://localhost:5001
    ports:
      - "5173:5173"

volumes:
  mysql_data:
